// Registers every Mongoose model once, so route files can pull them from one place.
module.exports = {
  User:             require('./User'),
  ActivityLog:      require('./ActivityLog'),
  Category:         require('./Category'),
  Product:          require('./Product'),
  PriceHistory:     require('./PriceHistory'),
  Offer:            require('./Offer'),
  Conversation:     require('./Conversation'),
  Message:          require('./Message'),
  Cart:             require('./Cart'),
  Order:            require('./Order'),
  Payment:          require('./Payment'),
  Delivery:         require('./Delivery'),
  Dispute:          require('./Dispute'),
  Review:           require('./Review'),
  ReviewVote:       require('./ReviewVote'),
  Wishlist:         require('./Wishlist'),
  SavedSearch:      require('./SavedSearch'),
  BlogCategory:     require('./BlogCategory'),
  BlogPost:         require('./BlogPost'),
  BlogComment:      require('./BlogComment'),
  Tag:              require('./Tag'),
  ForumPost:        require('./ForumPost'),
  ForumReply:       require('./ForumReply'),
  Vote:             require('./Vote'),
  FaqCategory:      require('./FaqCategory'),
  FaqEntry:         require('./FaqEntry'),
  FaqSubmission:    require('./FaqSubmission'),
  ModerationReport: require('./ModerationReport'),
  Studio:           require('./Studio'),
  StudioBooking:    require('./StudioBooking'),
  Advertisement:    require('./Advertisement'),
  Notification:     require('./Notification'),
  AdminAction:      require('./AdminAction'),
  AnalyticsDaily:   require('./AnalyticsDaily'),
  SitemapEntry:     require('./SitemapEntry')
};
